# ── Stage 1 : Build Angular ──────────────────────────────
FROM node:22-alpine AS builder
WORKDIR /app
COPY frontend/package*.json ./
RUN npm ci --prefer-offline
COPY frontend/ .
RUN npm run build -- --configuration production --output-path=/app/dist

# ── Stage 2 : Serveur Nginx ───────────────────────────────
FROM nginx:alpine
COPY --from=builder /app/dist/homely-front /usr/share/nginx/html
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
